### PR TITLE
Add linter

### LINKED ISSUE #1: Add a Linter
Add [ESLint](https://eslint.org/) for the linter with [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react) and [eslint-config-prettier](https://www.npmjs.com/package/eslint-config-prettier).

### PR DESCRIPTION
**Pull request by ryohilmi**
closes #1

### CODE REVIEW

**Review by maroqijalil — COMMENTED** [review]
Merge the pull request of adding a license to this pull request

**Review by maroqijalil — COMMENTED** [review]
add contributing.md file

**Review by maroqijalil — APPROVED** [review]
LGTM

**Review by threeal — APPROVED** [review]
Looks good to me.

**Pull request merged**
